name: knote
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.10+1

environment:
  sdk: ">=2.14.0 <3.0.0"
# todo : before v1.5.0
# - Convex Appbar
# -
# -
# ----------------

dependencies:

  #share_plus: ^3.0.1
  share:
    ^2.0.4
  badges:
    ^1.2.0
  flutter_slidable:
    ^0.6.0


  #todo :
  #- url_launcher: ^6.0.3
  #- image_picker: ^0.7.3

  animations:
    ^2.0.0
  package_info:
    ^2.0.2

  #intl: ^0.17.0

  path_provider:
    ^2.0.2
  objectbox_flutter_libs: ^0.14.0
  objectbox: ^0.14.0

  #hive: ^2.0.4
  #hive_flutter: ^1.1.0

  #cached_network_image: ^2.5.0
  pedantic:
    ^1.11.0

  #todo : share: ^2.0.0
  equatable:
    ^2.0.3
  formz:
    ^0.4.0
  flutter_bloc:
    ^7.0.0
  google_sign_in:
    ^5.0.4
  ##google_fonts: ^1.1.0
  #google_maps_flutter: ^0.5.32

  #hive: ^2.0.2
  #firebase_storage: ^4.0.1
  #cloud_functions: ^0.6.0+1
  cloud_firestore:
    ^2.4.0
  firebase_core:
    ^1.4.0
  firebase_auth:
    ^3.0.0
  firebase_database:
    ^6.1.2

  font_awesome_flutter:
    ^9.1.0
  #smooth_star_rating: ^1.1.1

  mime:
    ^1.0.0
  open_file:
    ^3.2.1
  uuid:
    ^3.0.4
  file_picker:
    ^3.0.3

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  utils_component:
    git:
      url: https://github.com/lordyhas/utils_component
    #path: ../packages/utils_component

dev_dependencies:
  build_runner: ^1.0.0
  objectbox_generator: ^0.14.0
  #hive_generator: ^1.1.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

#To generate ObjectBox binding code for your entities,
# run: flutter pub run build_runner build

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/avatar/avatar_image1.jpg
    - assets/avatar/IMG.jpg
    - assets/bg_image/bg1.png
    - assets/bg_image/bg2.png
    - assets/bg_image/bg3.png
    - assets/bg_image/bg4.png
    - assets/bg_image/bg_image1.jpg
    - assets/bg_image/bg_image2.jpg
    - assets/bg_image/bg_image3.jpg
    - assets/images/feedbackImage.png
    - assets/images/helpImage.png
    - assets/images/inviteImage.png
    - assets/images/logo_1.png
    - assets/images/logo_2.png
    - assets/images/profile1.png
    - assets/images/supportIcon.png
    - assets/images/userImage.png
    - assets/images/userImage1.JPG
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg


  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-Regular.ttf
        - asset: fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 400

#flutter_intl:
  #enabled: true