// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyitGqRgH2kp8EKX7_f1Jh0KQW4ulSUk4',
    appId: '1:1087224321015:web:72ac732e10074fa72714f2',
    messagingSenderId: '1087224321015',
    projectId: 'parents-data-8c0ee',
    authDomain: 'parents-data-8c0ee.firebaseapp.com',
    databaseURL: 'https://parents-data-8c0ee-default-rtdb.firebaseio.com',
    storageBucket: 'parents-data-8c0ee.appspot.com',
    measurementId: 'G-70EYK37DFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9xbo2Spvxr4eOyczF0GJim6O5pGQOcXY',
    appId: '1:1087224321015:android:31397d414885df7c2714f2',
    messagingSenderId: '1087224321015',
    projectId: 'parents-data-8c0ee',
    databaseURL: 'https://parents-data-8c0ee-default-rtdb.firebaseio.com',
    storageBucket: 'parents-data-8c0ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQPRE3JmiYi0TBKzTVu5ETcNA7OMRy91M',
    appId: '1:1087224321015:ios:dbaf76c262ffab922714f2',
    messagingSenderId: '1087224321015',
    projectId: 'parents-data-8c0ee',
    databaseURL: 'https://parents-data-8c0ee-default-rtdb.firebaseio.com',
    storageBucket: 'parents-data-8c0ee.appspot.com',
    androidClientId: '1087224321015-k6g45o4b7a6oknadbkeolclfkg10o226.apps.googleusercontent.com',
    iosClientId: '1087224321015-o550ae6drdhs2mg4raek92uc4orauorq.apps.googleusercontent.com',
    iosBundleId: 'com.kdynamic.knote',
  );
}
