/// Generated by AssetsRefGenerator on 2021/09/29
class Res {
  static const String avatar_image1 = "assets/avatar/avatar_image1.jpg";
  static const String bg1 = "assets/bg_image/bg1.png";
  static const String bg2 = "assets/bg_image/bg2.png";
  static const String bg3 = "assets/bg_image/bg3.png";
  static const String bg4 = "assets/bg_image/bg4.png";
  static const String bg_image1 = "assets/bg_image/bg_image1.jpg";
  static const String bg_image2 = "assets/bg_image/bg_image2.jpg";
  static const String bg_image3 = "assets/bg_image/bg_image3.jpg";
  static const String feedbackImage = "assets/images/feedbackImage.png";
  static const String helpImage = "assets/images/helpImage.png";
  static const String IMG = "assets/avatar/IMG.jpg";
  static const String inviteImage = "assets/images/inviteImage.png";
  static const String logo_1 = "assets/images/logo_1.png";
  static const String logo_2 = "assets/images/logo_2.png";
  static const String profile1 = "assets/images/profile1.png";
  static const String supportIcon = "assets/images/supportIcon.png";
  static const String userImage = "assets/images/userImage.png";
  static const String userImage1 = "assets/images/userImage1.JPG";
}
